// Optional audio-enhancement pipeline for recordings the administrator OWNS or has
// PERMISSION to process. It is never applied to third-party (e.g. YouTube) content.
//
// Guarantees:
//  - the ORIGINAL upload is stored once, made read-only, and never modified;
//  - every enhancement run writes a NEW file and a new ENHANCED AudioAsset row;
//  - files live in STORAGE_DIR (outside /public) and are only served for
//    recordings marked as authorized.

import { spawn } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { chmod, mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { prisma } from "./db";

export const AUDIO_EXTENSIONS: Record<string, string> = {
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".flac": "audio/flac",
  ".m4a": "audio/mp4",
  ".aac": "audio/aac",
  ".ogg": "audio/ogg",
  ".oga": "audio/ogg",
  ".opus": "audio/ogg",
  ".webm": "audio/webm",
  ".mp4": "video/mp4",
};

export interface EnhanceSettings {
  noiseReduction: "off" | "light" | "medium" | "strong";
  humReduction: "off" | "50" | "60"; // mains frequency (Israel: 50 Hz)
  hissReduction: boolean;
  normalize: boolean; // EBU R128 loudness normalization
  vocalClarity: boolean;
  dynamicRange: "off" | "gentle" | "strong";
  trimSilence: boolean; // leading/trailing silence only
}

export const DEFAULT_ENHANCE_SETTINGS: EnhanceSettings = {
  noiseReduction: "medium",
  humReduction: "50",
  hissReduction: true,
  normalize: true,
  vocalClarity: true,
  dynamicRange: "gentle",
  trimSilence: true,
};

export function storageDir(): string {
  return path.resolve(process.env.STORAGE_DIR || "./storage");
}

export function assetFilePath(fileName: string): string {
  // fileName is generated by us (uuid + ext); still guard against traversal.
  const safe = path.basename(fileName);
  return path.join(storageDir(), safe);
}

/** Build the ffmpeg -af filter chain for the selected settings. */
export function buildFilterChain(s: EnhanceSettings): string {
  const f: string[] = [];
  // Remove sub-audible rumble (handling noise, wind, HVAC).
  f.push("highpass=f=60");
  if (s.humReduction !== "off") {
    const base = Number(s.humReduction);
    // Narrow notches on the mains fundamental and first harmonics.
    for (const mult of [1, 2, 3, 4]) f.push(`equalizer=f=${base * mult}:t=q:w=12:g=-24`);
  }
  if (s.noiseReduction !== "off") {
    const nr = { light: 8, medium: 14, strong: 22 }[s.noiseReduction];
    f.push(`afftdn=nr=${nr}:nf=-40:tn=1`);
  }
  if (s.hissReduction) {
    // Gentle high-shelf cut and low-pass above the useful vocal/choir range.
    f.push("treble=g=-3:f=9000", "lowpass=f=14000");
  }
  if (s.vocalClarity) {
    // Reduce mud, add presence for chant intelligibility.
    f.push("equalizer=f=250:t=q:w=1:g=-2", "equalizer=f=3000:t=q:w=1.2:g=3");
  }
  if (s.dynamicRange !== "off") {
    f.push(
      s.dynamicRange === "gentle"
        ? "acompressor=threshold=-22dB:ratio=2:attack=25:release=300:makeup=2"
        : "acompressor=threshold=-26dB:ratio=4:attack=15:release=250:makeup=4",
    );
  }
  if (s.trimSilence) {
    // Trim leading silence, then trailing silence via reverse; internal pauses are kept.
    f.push(
      "silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.5",
      "areverse",
      "silenceremove=start_periods=1:start_threshold=-50dB:start_silence=0.5",
      "areverse",
    );
  }
  if (s.normalize) f.push("loudnorm=I=-16:TP=-1.5:LRA=11");
  return f.join(",");
}

export function parseEnhanceSettings(input: Partial<Record<keyof EnhanceSettings, unknown>>): EnhanceSettings {
  const d = DEFAULT_ENHANCE_SETTINGS;
  const pick = <T extends string>(v: unknown, allowed: readonly T[], fallback: T): T =>
    typeof v === "string" && (allowed as readonly string[]).includes(v) ? (v as T) : fallback;
  const bool = (v: unknown, fallback: boolean) =>
    v === undefined ? fallback : v === true || v === "on" || v === "true" || v === "1";
  return {
    noiseReduction: pick(input.noiseReduction, ["off", "light", "medium", "strong"] as const, d.noiseReduction),
    humReduction: pick(input.humReduction, ["off", "50", "60"] as const, d.humReduction),
    hissReduction: bool(input.hissReduction, d.hissReduction),
    normalize: bool(input.normalize, d.normalize),
    vocalClarity: bool(input.vocalClarity, d.vocalClarity),
    dynamicRange: pick(input.dynamicRange, ["off", "gentle", "strong"] as const, d.dynamicRange),
    trimSilence: bool(input.trimSilence, d.trimSilence),
  };
}

function ffmpegBin(): string {
  return process.env.FFMPEG_PATH || "ffmpeg";
}

function run(bin: string, args: string[]): Promise<{ code: number; stderr: string }> {
  return new Promise((resolve) => {
    const p = spawn(bin, args, { stdio: ["ignore", "ignore", "pipe"] });
    let stderr = "";
    p.stderr.on("data", (d: Buffer) => {
      stderr = (stderr + d.toString()).slice(-8000);
    });
    p.on("error", (e) => resolve({ code: -1, stderr: String(e) }));
    p.on("close", (code) => resolve({ code: code ?? -1, stderr }));
  });
}

export async function ffmpegAvailable(): Promise<boolean> {
  const r = await run(ffmpegBin(), ["-hide_banner", "-version"]);
  return r.code === 0;
}

async function sha256File(file: string): Promise<string> {
  const { createReadStream } = await import("node:fs");
  return new Promise((resolve, reject) => {
    const h = createHash("sha256");
    createReadStream(file)
      .on("data", (c) => h.update(c))
      .on("end", () => resolve(h.digest("hex")))
      .on("error", reject);
  });
}

/** Store an authorized original. The file is made read-only after writing. */
export async function saveOriginal(opts: {
  recordingId: string;
  data: Uint8Array;
  originalName: string;
  rightsStatement: string;
}) {
  const ext = path.extname(opts.originalName).toLowerCase();
  const mimeType = AUDIO_EXTENSIONS[ext];
  if (!mimeType) throw new Error(`Unsupported file type ${ext || "(none)"}`);
  await mkdir(storageDir(), { recursive: true });
  const fileName = `original-${randomUUID()}${ext}`;
  const full = assetFilePath(fileName);
  await writeFile(full, opts.data, { flag: "wx" });
  await chmod(full, 0o444);
  const sha256 = createHash("sha256").update(opts.data).digest("hex");
  return prisma.audioAsset.create({
    data: {
      recordingId: opts.recordingId,
      kind: "ORIGINAL",
      fileName,
      originalName: opts.originalName.slice(0, 200),
      mimeType,
      sizeBytes: opts.data.byteLength,
      sha256,
      rightsStatement: opts.rightsStatement,
    },
  });
}

/** Run the enhancement pipeline on an ORIGINAL asset, producing a new ENHANCED asset. */
export async function enhanceOriginal(originalId: string, settings: EnhanceSettings) {
  const original = await prisma.audioAsset.findUnique({
    where: { id: originalId },
    include: { recording: { select: { isAuthorized: true } } },
  });
  if (!original || original.kind !== "ORIGINAL") throw new Error("Original audio asset not found");
  if (!original.recording.isAuthorized) {
    throw new Error("Recording is not marked as original/authorized audio — enhancement refused");
  }
  const input = assetFilePath(original.fileName);
  const fileName = `enhanced-${randomUUID()}.m4a`;
  const output = assetFilePath(fileName);
  const shaBefore = original.sha256;

  const asset = await prisma.audioAsset.create({
    data: {
      recordingId: original.recordingId,
      kind: "ENHANCED",
      parentId: original.id,
      fileName,
      mimeType: "audio/mp4",
      sizeBytes: 0,
      sha256: "",
      settings: JSON.stringify(settings),
      rightsStatement: original.rightsStatement,
      status: "PROCESSING",
    },
  });

  const args = [
    "-hide_banner",
    "-nostdin",
    "-i",
    input,
    "-vn", // audio only
    "-af",
    buildFilterChain(settings),
    "-ar",
    "48000",
    "-c:a",
    "aac",
    "-b:a",
    "192k",
    "-movflags",
    "+faststart",
    "-n", // never overwrite
    output,
  ];
  const r = await run(ffmpegBin(), args);
  if (r.code !== 0) {
    await rm(output, { force: true });
    return prisma.audioAsset.update({
      where: { id: asset.id },
      data: { status: "FAILED", error: r.stderr.split("\n").slice(-6).join("\n") },
    });
  }
  // Paranoid check that the original is unchanged.
  const shaAfter = await sha256File(input);
  if (shaAfter !== shaBefore) throw new Error("Original file changed during processing — aborting");
  const st = await stat(output);
  return prisma.audioAsset.update({
    where: { id: asset.id },
    data: { status: "READY", sizeBytes: st.size, sha256: await sha256File(output) },
  });
}

export async function deleteAsset(id: string) {
  const asset = await prisma.audioAsset.findUnique({ where: { id } });
  if (!asset) return;
  // Deleting an original also deletes the enhanced versions derived from it.
  const children = asset.kind === "ORIGINAL" ? await prisma.audioAsset.findMany({ where: { parentId: id } }) : [];
  for (const a of [...children, asset]) {
    await rm(assetFilePath(a.fileName), { force: true });
    await prisma.audioAsset.delete({ where: { id: a.id } });
  }
}
